#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Import common cmd
source ./experimental_helper.sh
source ./_common.sh

#=================================================

ynh_script_progression "Updating NGINX web server configuration..."
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

ynh_script_progression "Stoping services..."

# Stop service before any change
ynh_systemctl --service=seafile --action=stop
ynh_systemctl --service=seahub --action=stop
sleep 2
pkill -f seafile-controller || true
pkill -f seaf-server || true
pkill -f ccnet-server || true
pkill -f seahub || true

ynh_script_progression "Updating seafile configuration..."

# Update Seafile Config
ynh_config_add --jinja --template=seahub_settings.py --destination="$install_dir"/conf/seahub_settings.py
ynh_config_add --template=ccnet.conf --destination="$install_dir"/conf/ccnet.conf
ynh_config_add --template=gunicorn.conf.py --destination="$install_dir"/conf/gunicorn.conf.py
ynh_config_add --template=seafdav.conf --destination="$install_dir"/conf/seafdav.conf

# Update permissions
ynh_permission_url --permission=file_server --url="$domain"/seafhttp
ynh_permission_url --permission=webdav --url="$domain"/seafdav

# Clean url in config in DB
clean_url_in_db_config

# Avoid the current effect
sleep 2

# Reload services
ynh_script_progression "Starting services..."
ynh_systemctl --service=seafile --wait_until="spawned seaf-server, pid " --log_path=/var/log/seafile/controller.log
sleep 2
ynh_systemctl --service=seahub --wait_until="Seahub is started" --log_path="systemd"
sleep 2

ynh_script_progression "Change of URL completed for $app" --time=
